# Generated by Django 5.0.6 on 2024-06-25 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0002_alter_education_file_alter_projects_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='de',
        ),
    ]
