# Generated by Django 5.0.6 on 2024-06-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0003_remove_workexperience_de'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='title',
            field=models.CharField(max_length=254),
        ),
    ]
